/*
Problem 2
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include<stdio.h>

int main(void)
{
    int p1 = 1, p2 = 1, new, sum = 0;
    while(new <= 4000000){
        new = p1 + p2;
        p1 = p2;
        p2 = new;
        if (new % 2 == 0)
            sum += new;
    }
    printf("The sum of even valued Fibonacci numbers below 4 million is %d\n", sum);
    return 0;
}
